本书配套视频课程：[解剖深度学习原理，从0实现深度学习库](https://ke.qq.com/course/2900371?tuin=ac5537fd) 

更多代码或学习资料将向购买视频课程或书的学生提供。


+ 博客网站：[https://hwdong-net.github.io](https://hwdong-net.github.io)
+ youtube频道: [hwdong](http://www.youtube.com/c/hwdong)
+ bilibili网站：[hw-dong](https://space.bilibili.com/281453312)

## numpy张量库


### 1.2.2 创建ndarray对象

#### array()函数

In [1]:
import numpy as np
a= np.array([1,3,2])   #创建一维向量（张量）a
print(a)
print(a.shape)
b= np.array([[1,3,2],[4,5,6]])   #创建二维向量（张量）b
print(b)
print(b.shape) #axis=0

[1 3 2]
(3,)
[[1 3 2]
 [4 5 6]]
(2, 3)


array()会根据传入的可迭代对象元素的类型创建相应元素类型的数组，也可以通过指定参数dtype创建相应数据元素类型的数组。

In [2]:
a = np.array([1,2,3,4])
print(a.dtype)
print(a)
b = np.array([1,2,3,4], dtype=np.float64)
print(b.dtype)
print(b)

int32
[1 2 3 4]
float64
[1. 2. 3. 4.]


ndarray的属性

In [3]:
a= np.array([1.,2.,3.]) 
print(a.ndim,a.shape,a.size,a.dtype,a.itemsize,a.data)

b= np.array([[1,2,3],[4,5,6]]) 
print(b.ndim,b.shape,b.size,b.dtype,b.itemsize,b.data)

1 (3,) 3 float64 8 <memory at 0x000001FB9BD45E80>
2 (2, 3) 6 int32 4 <memory at 0x000001FB8D922790>


可以通过下标访问多维数组的元素，称为**索引**，下标从0开始，例如访问b的第2行第3列元素，可以用下标[1,2]取访问：

In [4]:
print(a[2])
print(b[1,2])

3.0
6


####  asarray()

asarray()创建新的ndarray对象和传入的对象共享同一数据存储。

In [6]:
d= np.asarray(range(5)) 
print(d)
e= np.asarray([1,2,3,4,5])     # 通过asarray也可以从一个序列或可迭代对象创建一个ndarray数组对象
print(e)
print(type(e))

f= np.asarray(e)           #f和e共享同一个数据存储，修改一个就会影响另外一个
e[2] = 20                  #可通过下标2访问e的第3个元素
print(e)
print(f)

[0 1 2 3 4]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 1  2 20  4  5]
[ 1  2 20  4  5]


#### ndarray的tolist()方法

将一个ndarray对象转变为一个python的list对象，如：

In [7]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.tolist()
print(type(b))
print(b)

<class 'list'>
[[1, 2, 3], [4, 5, 6]]


#### astype()和reshape()

ndarray的astype() 方法将一个ndarray对象的元素的数据类型转换成另外一种数据类型，

In [8]:
c = a.astype(np.float64)   
print(a.dtype,c.dtype)
a[0][0] = 100
print(a)
print(c)

int32 float64
[[100   2   3]
 [  4   5   6]]
[[1. 2. 3.]
 [4. 5. 6.]]


numpy的reshape()函数或ndarray的reshape() 方法可通过改变ndarray对象的形状方法创建一个新的ndarray对象。如：

In [9]:
a= np.array(range(6)) 
b =np.reshape(a,(2,3)) 
c = a.reshape(2,3).astype(np.float64)
print(a)
print(b)
print(c)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0. 1. 2.]
 [3. 4. 5.]]


#### arange()和linspace()

arange()函数通过指定开始值、终值和步长创建表示等差数列的一维数组。
```python
numpy.arange([start], stop, [step], dtype=None)
```

In [ ]:
print(np.arange(5))  #只指定end,start和step默认为0和1
print(np.arange(2,5))
print(np.arange(2,7,2))

和arange()类似，linspace()也用于创建一个初始值和终值之间的等差数列，只不过其第三个参数不是步长而是创建的元素的数目。

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

linspace()在start和stop之间创建num个数构成的等差数列。endpoint指示是否包含stop。

In [11]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [12]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

类似于linspace，logspace()创建一个等比数列。

numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

logspace()先产生在start和stop之间的一个等差数列，再以base（base默认值为10）为底，以这些数作为指数，产生一个等比数列作为创建的numpy数组的元素。

In [13]:
np.logspace(2.0, 3.0, num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [14]:
np.logspace(2.0, 3.0, base = 3,num=5)

array([ 9.        , 11.84466612, 15.58845727, 20.51556351, 27.        ])

####  full()、empty()、zeros()、ones()、eye()

In [15]:
np.full((2, 3),np.inf)

array([[inf, inf, inf],
       [inf, inf, inf]])

In [16]:
np.full((2, 3),3.5)

array([[3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5]])

In [17]:
print( np.empty((2,3)) ,'\n')    # 创建形状为 (2,3)的二维数组，即相当于2*3的矩阵.元素的值未初始化
print( np.zeros((2,3)) ,'\n')   # 创建形状为 (2,3)元素值都是0的二维数组，即相当于2*3的矩阵
print( np.ones((1,2)) ,'\n' )   # 创建形状为 (1,2)元素值都是1的二维数组
print(  np.eye(2)   ,'\n' )     #创建形状为 (2,2)的单位矩阵，即对角线元素值为1，其他元素值都是0的矩阵

[[3.5 3.5 3.5]
 [3.5 3.5 3.5]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1.]] 

[[1. 0.]
 [0. 1.]] 



####  创建随机值张量的常用函数

In [18]:
np.random.rand(2,3)

array([[0.37287844, 0.73462798, 0.2725476 ],
       [0.09215323, 0.08142553, 0.39056221]])

In [19]:
e = np.random.random((2,3))  # 创建形状为 (2,3)的元素值都是[0,1]之间的随机数的二维数组
print(e)   

[[0.78049868 0.59858685 0.40819972]
 [0.35385777 0.73980844 0.4145988 ]]


In [20]:
a = np.random.randn(5)        #生成5个服从(0,1)标准正态分布的随机数的一维数组
b = np.random.randn(2,3)        #生成形状为(2,3)服从(0,1)标准正态分布的随机数的二维数组
print("a:",a)
print("b:",b)
c = np.random.normal(0,1,5)        #生成5个服从(0,1)标准正态分布的随机数的一维数组
d = np.random.normal(size=(2,3))   #生成size是(2,3）服从(0,1)标准正态分布的随机数的二维数组
e = np.random.normal(2,0.3,size=(2,3))  #生成size是(2,3）服从(2,0.3)正态分布的随机数的二维数组
print("c:",c)
print("d:",d)
print("e:",e)

print(a.shape,b.shape,c.shape,d.shape)

a: [ 2.67015352  0.7075645  -2.75907281  0.86318258 -0.08484908]
b: [[-1.13137719 -0.03767489  0.46301793]
 [-0.8753315   0.47252176 -0.71935943]]
c: [ 0.21980379 -0.25845182  0.84023704 -0.68930176 -1.25869097]
d: [[ 0.73014298  0.40774575 -0.19230705]
 [ 0.91937882 -0.18844764 -0.5762938 ]]
e: [[1.59441259 1.51212102 2.54609328]
 [2.18860168 2.01901038 2.43592927]]
(5,) (2, 3) (5,) (2, 3)


可以将一般的正态分布转化为标准正态分布$z\backsim N(0,1)$

In [23]:
mu, sigma = 2, 0.3
e = np.random.normal(mu, sigma,size=(2,3)) 
print(e)
f = np.random.randn(2,3) 
print(f)
g = f*sigma+mu             # f= (g-mu)/sigma服从标准正太分布，g服从(mu,sigma)高斯分布
print(g)

[[1.95872477 2.20936964 2.01858481]
 [2.04816291 1.48283688 1.84673311]]
[[0.55591769 1.2117312  0.54753238]
 [0.31462126 0.76717955 0.3354586 ]]
[[2.16677531 2.36351936 2.16425971]
 [2.09438638 2.23015386 2.10063758]]


random()函数有一个别名函数random_sample()，即两者是同一个函数，都生成[0,1]区间的均匀采样的随机数。

In [24]:
5 * np.random.random_sample((2, 3)) +2

array([[3.22317867, 6.75413051, 3.45074588],
       [6.0667209 , 4.41510161, 6.63281013]])

#### 添加、重复与铺设、合并与分裂、边缘填充、添加轴与交换轴

nunmpy的**append()** 可以在已有数组后面添加内容创建一个新的数组，其函数规范是：
```
numpy.append(arr, values, axis=None)
```
表示在数组arr后面添加values的内容，axis表示沿着那个轴添加，默认为None，将创建一个摊平（扁平）的一维数组。

In [26]:
a = np.array([1,2,3])
b= np.append(a,4)
print(a)
print(b)
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

[1 2 3]
[1 2 3 4]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

重复函数**repeat()** 通过沿着某个轴重复数组中元素的方式创建一个新的ndarray数组。

```numpy.repeat(a, repeats, axis=None)```

创建一个新的数组，将a的元素沿着轴axis重复repeats次。axis默认值是None，表示创建一个摊平（扁平）的数组。

In [28]:
np.repeat(3, 4)  #创建一个数组，将数值3重复4次

array([3, 3, 3, 3])

In [29]:
a = np.array([[1,2],[3,4]])
np.repeat(a, 2)             #创建一个摊平的数组，即一维数组，其中元素是x中元素重复了2次

array([1, 1, 2, 2, 3, 3, 4, 4])

In [30]:
np.repeat(a, 2,axis=0)   

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [31]:
np.repeat(a, 2,axis=1)   

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

铺设函数**tile(A, reps)** 可将整个数组像tile（瓷砖）一样的纵向或横向复制。
```python
numpy.tile(A, reps)
```

In [32]:
a = np.array([1, 2,3])
b= np.tile(a, 2)   #a重复2次的方式创建一个新的数组
print(a)
print(b)

[1 2 3]
[1 2 3 1 2 3]


将数组a按形状(2, 2)方式铺设时，会先将a从一维张量[1, 2, 3]提成为二维张量[[1, 2, 3]]，再进行铺设：

In [33]:
np.tile(a, (2, 2))   # a2行2列的方式平铺，创建一个新数组

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

下面的c形状是(1，2)，而reps=2的长度为1，reps会先变为(1,2)，再进行铺设，即axis=0重复1次（即行方向上保持不变），而axis=2重复2次。

In [34]:
c = np.array([[1, 2], [3, 4]])
print(c)
np.tile(c, 2)  #reps会先变为(1,2)表示第1轴重复1次，第2轴重复2次

[[1 2]
 [3 4]]


array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [35]:
np.tile(c, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

拼接函数**concatenate()**沿着指定轴axis拼接多个数组，创建一个新的数组。
```
numpy.concatenate((a1, a2, …), axis=None, out=None)
```

axis指定合并方向的轴，默认值是0，如果是None，表示合并成一个扁平的数组，即一维数组。out默认为None，如果不是None，则合并结果将放到out里。

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(b.T)
c = np.concatenate((a, b), axis=0)         #沿axis=0轴进行合并
d = np.concatenate((a, b.T), axis=1)       #沿axis=1轴进行合并
e = np.concatenate((a, b), axis=None)      #合并成一个扁平的数组
print(c)
print(d)
print(e)

[[5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


叠加函数**stack**(arrays, axis=0, out=None)将一系列数组沿着axis的方向堆积（合并）成一个新的数组，axis值默认为0，表示第一个轴。如果axis=-1表示最后的轴。

In [37]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
np.stack((a, b,c))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.stack((a,b,c),axis=1)

array([[1, 3, 5],
       [2, 4, 6]])

作为stack()的特殊情形，numpy.column_stack(tup) 将tup中的一系列一维数组作为二维数组的列创建一个二维数组。如下面代码将2个一维数组作为新数组的列：

In [39]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

作为concatenate()的特殊情形，**numpy.hstack(tup)** 沿着第2个轴（axis=1）进行拼接，或者说沿着水平方向（列）进行拼接。如：

In [40]:
a = np.array([[1],[2],[3]])       #3行1列
b = np.array([[4],[5],[6]])       #3行1列
print(a.shape,b.shape)
np.hstack((a,b))                  #合并3行2列

(3, 1) (3, 1)


array([[1, 4],
       [2, 5],
       [3, 6]])

对一维数组的合并，仍然是一个一维数组：

In [41]:
a = np.array((1,2,3))      
b = np.array((4,5,6))
print(a.shape,b.shape)
np.hstack((a,b))

(3,) (3,)


array([1, 2, 3, 4, 5, 6])

作为concatenate()的特殊情形，**numpy.vstack(tup)** 沿着第1个轴（axis=0）进行拼接，或者说沿着垂直方向（行）进行拼接。如：

In [42]:
a = np.array([[1, 2, 3]])   #1行3列
b = np.array([[4, 5, 6]])   #1行3列
print(a.shape)
np.vstack((a,b))            #合并为2行3列

(1, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
c = np.array([[1], [2], [3]])   #有3行
d = np.array([[4], [5], [6]])   #有3行
np.vstack((c,d))                #合并为6行

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

vstack()对于一维数组(N,)会看成(1,N)的形状进行拼接。如：

In [44]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))   # 1D数组a形状是(3,)会被看成(1,3)的2D数组，b也同样如此

array([[1, 2, 3],
       [4, 5, 6]])

**分裂**是和合并相反的操作，函数**split()**沿着axis对数组进行分裂（axis默认值为0）
```
numpy.split(ary, indices_or_sections, axis=0)
```
indices_or_sections如果是整数N，表示分裂成N个相等的子数组，如果不可能做到，则失败。indices_or_sections如果是排序的整数数组，表示在轴方向上分裂的位置。如```indices_or_sections = [2,3]```、axis=0，其分裂的结果是：
- ```ary[:2]```
- ```ary[2:3]```
- ```ary[3:]```

In [46]:
x = np.arange(9.0)
print(x)
np.split(x, 3)   #分裂成3个长度相等的子数组

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [47]:
x = np.arange(8.0)
print(x)
np.split(x, [3, 5, 6, 10]) 

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

hsplit()、vsplit()分别是对应合并操作hstack()、vstack()的分裂函数，分别沿水平（axis=1）和垂直方向（axis=0）对数组分裂。这2个分裂函数都是分裂函数split()的特殊情形。

In [48]:
x = np.arange(16.0).reshape(4, 4)
print(x)
np.hsplit(x, 2)                 #沿水平方向（列方向）分裂成2个相等的子数组

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [49]:
np.vsplit(x, 2)             #沿垂直方向（行方向）分裂成2个相等的子数组

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

np.pad()函数可以对数组的每一轴（维）进行边缘填充，即在每一轴（维）的前后边缘位置填充一些数值。
```
numpy.pad(array, pad_width, mode='constant', **kwargs)
```
arrar是输入数组，pad_width表示填充的宽度（元素的个数），而mode表示填充的方式，'constant'表示填充的常量，constant_values表示常量的值。如：

In [50]:
a = [7,8 ,9 ]
b =np.pad(a, (2, 3), mode='constant', constant_values=(4, 6))
print(a)
print(b)

[7, 8, 9]
[4 4 7 8 9 6 6 6]


In [51]:
np.pad(a, (2, 3), 'edge')

array([7, 7, 7, 8, 9, 9, 9, 9])

mode='minimum'表示用数组中的最小值填充。对于多维数组，必须指定每一维的首尾填充的宽度。

In [52]:
a = [[2, 5], [7, 9]]
print(a)
np.pad(a, ((1, 2), (2, 3)), 'minimum')

[[2, 5], [7, 9]]


array([[2, 2, 2, 5, 2, 2, 2],
       [2, 2, 2, 5, 2, 2, 2],
       [7, 7, 7, 9, 7, 7, 7],
       [2, 2, 2, 5, 2, 2, 2],
       [2, 2, 2, 5, 2, 2, 2]])

**numpy.expand_dims(a, axis)** 在轴axis位置插入一个新轴，从而扩展了数组的形状。如：

In [53]:
x = np.array([3,5])                  #x是一维数组，只有1个轴
print(x.shape)
print(x)
y = np.expand_dims(x, axis=0)           #y是二维数组，有2个轴，新增加的是轴axis=0，即新增加的轴成为第一个轴（行）
print(y.shape)
print(y)

(2,)
[3 5]
(1, 2)
[[3 5]]


也可以用np.newaxis给x添加一个轴，如：

In [54]:
y = x[np.newaxis,:]
print(y.shape)
print(y)

(1, 2)
[[3 5]]


In [55]:
y = x[:,np.newaxis]
print(y.shape)
print(y)

(2, 1)
[[3]
 [5]]


时需要交换数组的轴，例如读取彩色图像时，其颜色通道可能是第3轴（axis=2），但在一些程序中，颜色通道需要在第一轴。有几个不同的函数可用于交换数组的轴。

**numpy.swapaxes(a, axis1, axis2)**交换轴axis1和axis2。如：

In [56]:
A = np.random.random((2,3,4,5))
print(A.shape)
B = np.swapaxes(A,0,2)  #交换axos=0和axis=2的轴
print(B.shape)

(2, 3, 4, 5)
(4, 3, 2, 5)


**numpy.rollaxis(a, axis, start=0)**将轴axis向后滚动，直到位于轴start前面。如：

In [57]:
C = np.rollaxis(A,2,0)  # 将A的axis=2轴移动到axis=0轴前面，即C形状为：(4,23,,5)  
print(C.shape) 
D = np.rollaxis(C,2,1)  #将C的axis=2轴移动到axis=1轴前面，即D形状为(4,3,2,5)
print(D.shape) 

(4, 2, 3, 5)
(4, 3, 2, 5)


**numpy.moveaxis(a, source, destination)**将轴source移到轴destination位置。如:

In [58]:
C = np.moveaxis(A,2,0)  #A (2,3,4,5) C形状为(4,2,3,5)
print(C.shape) 
D = np.rollaxis(C,2,1)  #D形状为(4,3,2,5)
print(D.shape) 

(4, 2, 3, 5)
(4, 3, 2, 5)


**numpy.transpose(a, axes=None)** 根据axes中的轴的次序对数组的轴进行重新排列。axes默认值为None，表示对轴逆序排列。这是一个更加通用灵活的函数。如：

In [59]:
A = np.random.random((2,4))
print(A)
B = np.transpose(A)
print(B)
C = np.random.random((2,4,3,5))
D = np.transpose(C,(2,0,3,1))
print(D.shape)

[[0.5792545  0.59593983 0.66129472 0.38074224]
 [0.6356957  0.30193382 0.39393863 0.86570722]]
[[0.5792545  0.6356957 ]
 [0.59593983 0.30193382]
 [0.66129472 0.39393863]
 [0.38074224 0.86570722]]
(3, 2, 5, 4)


### 1.2.3  ndarry数组的索引和切片

numpy的索引（indexing）和切片（slicing）功能和python对序列对象的索引和切片是一样的，就是通过方括号```[]```指定元素下标的方式提取数组的一个子数组（元素）。

和python不同的是，numpy数组的索引和切片不是创建一个新的数组，而是原数组的一个视图（视窗），即切片的子数组就是原数组的一部分，因此，通过这个这个切片的引用变量去修改这个切片，实际修改的就是原数组。如：

In [60]:
import numpy as np
a = np.array([1,2,3,4,5])   # 创建秩是1的数组，即一维数组
print(a[0], a[1], a[2])   # 通过下标[]访问数组a的元素，打印它们，输出：1 2 3
a[0] = 5                  # 修改下标0的元素a[0]的值
print(a)                  # 打印整个数组，输出：5, 2, 3
b  = a[1:4]               # a[1:4]返回下标1开始，直到下标4（不包含下标4）的元素构成的数组的切片
print(b) 
b[0] = 40                 #切片b是a的一部分，修改b就是修改a中的元素
print(b) 
print(a)

1 2 3
[5 2 3 4 5]
[2 3 4]
[40  3  4]
[ 5 40  3  4  5]


索引和切片对多维数组是一样的，即可以对任意维进行索引或切片。

In [61]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[2,1])
print(a[2])
print(a[:,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10
[ 9 10 11 12]
[ 2  6 10]


也可以用负整数进行切片，如：

In [62]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, -1:-4:-1]    # 切片区域是：第一维从0到2（不包含2），第2维从-1到-4，步长是-1，不包含-4。
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[4 3 2]
 [8 7 6]]


某一维的索引或切片如果用```:```表示这一维的所有元素，如果指定范围```start:end:step```未指定步长step，则默认step=1，如果维指定start则默认为-，如果未指定end，则默认是这一维的最后位置+1。如：

In [63]:
c = a[:2,:]   #第一维默认end位置是2即第3行，而起始位置是0；第二维默认所有下标
print(c)
d = a[1:,1]   #第一维默认end位置是4，而起始位置是1；第二维是索引1.最后得到的是一个一维数组
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[ 6 10]


改变数组本身或切片，都使两者发生了改变，因为切片的数据就是原数组的一部分，即切片使原数组的一个窗口。

In [64]:
a[0,3]=100
print(a)
print(b)

[[  1   2   3 100]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   3   2]
 [  8   7   6]]


一个三维张量（数组）的索引例子：

In [65]:
a = np.array(range(27)).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [66]:
print(a[1, 2])

[15 16 17]


In [67]:
print(a[0,:,1])

[1 4 7]


In [68]:
print(a[:,1,2])

[ 5 14 23]


**整型数组索引**(Integer array indexing)

索引时，也可以给每一维索引传递不连续整数值。即给每一维传递的是一个整数数组。整型数组索引使得可以构建一个新的数组。如：

In [69]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
c = a[[0,2],[1,3]]  #第1行（0）、3行（2）和第2列、4列的元素
print(a)
print(c)
c[0] = 111
print(a)
print(c)       #说明c是独立于a的新的数组

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[111  12]


**布尔型数组索引(Boolean array indexing)** 

布尔型数组索引(Boolean array indexing)用于选取数组中满足某些条件的元素，例如：

In [70]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # 返回一个和a形状一样的值是True、False的数组
print(bool_idx)      # Prints "[[False False]
                     #          [ True True]
                     #          [ True True]]"

print(a[bool_idx])   # 根据布尔值是True和False元素
print(a[a > 2])      #可以将上述两式合为一式

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### 1.2.4 张量的计算

#### 1. 逐元素计算

前面已经看到对2个多维数组可以执行“逐元素”的```+、-、*、/、%```等运算，产生一个新的数组。如：

In [72]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a+b)
print(a*b)
print(b%a)

[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[0 0 0]
 [2 1 0]]


这些运算符还有对应的numpy函数，如add()、subtract()、multiply()、divide()是对应```+、-、*、/```运算符的函数。

In [73]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


numpy的函数都可以执行逐元素的计算，即对每个元素执行相应的运算，产生一个新的数组，如numpy的sqrt()、sin()、power()函数分别计算数组元素的平方根、正弦值、指数函数值：

In [74]:
print(np.sqrt(a))
print(np.sin(a))
print(np.power(a,2))   # 计算a的2次方

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 1  4  9]
 [16 25 36]]


逐元素乘积也称为**Hadamard乘积**或**Schur 乘积**。

#### 2. 累积计算

可用numpy的函数或ndarry类的方法对ndarry对象执行累积型计算，如求和（sum()）、求最值（min()、max()）、均值（mean()）、标准差（std()）。

In [76]:
a = np.array([[1,2,3],[4,5,6]]) 
print(np.max(a),a.max())
print(np.min(a),a.min())
print(np.sum(a),a.sum())
print(np.mean(a),a.mean())
print(np.std(a),a.std())

6 6
1 1
21 21
3.5 3.5
1.707825127659933 1.707825127659933


这些函数还可以指定沿着数组的哪一个轴进行运算，如：

In [77]:
print(a)
print(np.max(a,axis=0),a.max(axis=1))  # np.max(a,axis=0)表示沿着第0轴（第1维）的方向求最大值
print(np.min(a,axis=0),a.min(axis=1))
print(np.sum(a,axis=0),a.sum(axis=1))
print(np.mean(a,axis=0),a.mean(axis=0))
print(np.std(a,axis=0),a.std(axis=0))

[[1 2 3]
 [4 5 6]]
[4 5 6] [3 6]
[1 2 3] [1 4]
[5 7 9] [ 6 15]
[2.5 3.5 4.5] [2.5 3.5 4.5]
[1.5 1.5 1.5] [1.5 1.5 1.5]


#### 3.  点积

Hadamard乘积是逐元素的乘积，而张量的点积是**向量点积**和**矩阵乘积**的推广。

```
numpy.dot(a, b, out=None)
```
如果指定输出out，则结果输出到out里。

In [78]:
a= np.array([1,3]) 
b= np.array([2,5]) 
print("a*b:",a*b)
print("dot(a,b):",np.dot(a,b))         #两个向量的点积是一个数值（标量）

a*b: [ 2 15]
dot(a,b): 17


矩阵和向量的相乘需要注意其对应轴的元素个数是否一致，如：

In [79]:
a= np.array([[1,2,3],[4,5,6]]) 
b =  np.array([2,5]) 
c =  np.array([2,5,3]) 
print("a.shape:",a.shape)
print("b.shape:",b.shape)
print("c.shape:",c.shape)
#print("dot(a,b):",np.dot(a,b))
print("dot(b,a):",np.dot(b,a))
print("dot(a,c):",np.dot(a,c))

a.shape: (2, 3)
b.shape: (2,)
c.shape: (3,)
dot(b,a): [22 29 36]
dot(a,c): [21 51]


对于一维向量和二维矩阵，matmul()函数和运算符@也是执行矩阵乘法运算，和np.dot()具有相同作用。

In [80]:
a= np.array([1,3]) 
b= np.array([2,5]) 
print("dot(a,b):",np.dot(a,b))
print("matmul(a,b):",np.matmul(a,b))
print("a@b:",a@b)

a= np.array([[1,2,3],[4,5,6]]) 
b= np.array([[2,5],[1,3],[4,5]]) 
print("a.shape:",a.shape)          # 2*3矩阵
print("b.shape:",b.shape)          # 3*2矩阵
print("dot(a,b):",np.dot(a,b))
print("matmul(a,b):",np.matmul(a,b))
print("a@b:",a@b)

dot(a,b): 17
matmul(a,b): 17
a@b: 17
a.shape: (2, 3)
b.shape: (3, 2)
dot(a,b): [[16 26]
 [37 65]]
matmul(a,b): [[16 26]
 [37 65]]
a@b: [[16 26]
 [37 65]]


#### 4  广播Broadcasting

广播是一个强有力的机制，使得numpy可以对不同形状的数组进行算术运算。例如前面用一个数和一个数组进行运算。相当于将这个数变成和数组一样大小的数组，然后进行逐元素的运算。

In [81]:
a = np.array([[1,2],[3,4]]) 
print(a)

print(a+3)
print(a+ np.array([[3,3],[3,3]]))

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[4 5]
 [6 7]]


一个数和一个张量的减法、乘法、除法等也是执行这种广播计算。

In [82]:
print(a*3)
print(a/3)

[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


二维数组a可以和下面的一维数组b进行运算：

In [83]:
b = np.array([1,2]) 
print(a+b)

[[2 4]
 [4 6]]


In [84]:
a = np.array([[1],[2],[3]])   #a是(3,1)的二维数组
b = np.array([4,5])           #b是(2,)数组的一维数组
print(a)
print(b)
print(a+b)

[[1]
 [2]
 [3]]
[4 5]
[[5 6]
 [6 7]
 [7 8]]
