$(C\times kH \times kW)$

$(N\times oH \times oW)$

$(N\times oH \times oW)\times(C\times kH \times kW)$

$(C\times kH \times kW)\times F$

$C\times kH \times kW$

$N\times oH \times oW$

In [8]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
print(a)
np.reshape(a,-1)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])